feat: Integrate core sdk functionality
KeyValueSoftwareSystems/siren-vue-inbox pull request #4
Opened 2024-04-12 05:57 UTC by cizil-keyvalue

1. Integrate functionalities from 'test_notification'
2. Add event types
3. Add Siren Provider component
4. Adjust spacing in code

2024-04-12 06:11 UTC, nikhin-keyvalue requested changes

2024-04-12 06:11 UTC, nikhin-keyvalue commented on src/components/NotificationIcon.vue
> +  _type: string,
_type ??

2024-04-12 06:11 UTC, nikhin-keyvalue commented on src/components/NotificationIcon.vue
> +    //  handle error if needed
Arent we call errCallback here ? pls confirm with @bilta-keyvalue

2024-04-12 06:11 UTC, nikhin-keyvalue commented on src/components/SirenProvider.vue
> +  console.log(sirenValue, 'siren value');
Remove.

2024-04-12 06:11 UTC, nikhin-keyvalue commented on src/utils/commonUtils.ts
> +    console.log(`[${timestamp}] [${levelString}] ${message}`);
REmove if not needed

2024-04-12 11:03 UTC, cizil-keyvalue commented on src/components/NotificationIcon.vue
> +  _type: string,
type is not used, but it cannot be ignored since parameter is being passed by the pubsub library as part of its callback signature

2024-04-15 05:03 UTC, nikhin-keyvalue approved these changes

2024-04-15 05:03 UTC, merged