Update changes from core sdk
KeyValueSoftwareSystems/siren-vue-inbox pull request #7
Opened 2024-04-25 10:40 UTC by cizil-keyvalue

1.  Update default avatar.
2. Add avatar click and delete notification animation
3.  Update prop names.
4.  Update function names from 'test_notifications'
5.  Add verification status in Siren Provider
6.  Update stories
7.  Update modal width

2024-04-26 08:11 UTC, nikhin-keyvalue requested changes

2024-04-26 08:11 UTC, nikhin-keyvalue commented on src/components/NotificationCard.vue
> +import defaultAvatarDark from '../assets/dark/defaultAvatarDark.png';
Why are we using png not svg ??

2024-04-26 08:11 UTC, nikhin-keyvalue commented on src/components/NotificationCard.vue
> +  cardElement?.classList.add('siren-sdk-delete-animation');
Direct DOM Manipulation? Can't we use any other method ?

2024-04-27 05:03 UTC, bilta-keyvalue commented on src/components/LoaderComponent.vue
> +      <div :style="hideAvatar ? { width: '90%' } : { width: '80%' }" class="siren-sdk-card-loader-details">
can we avoid using inline styles

2024-04-27 05:53 UTC, bilta-keyvalue approved these changes

2024-04-27 06:11 UTC, merged